user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  option:
    size: 80
  app:
    views:
      size: 50
  controllers:
    users_controller:
      per_page: 5
    sessions_controller:
      remember_true: "1"
      remember_false: "0"
  integration:
    users_login_test:
      remember_true: "1"
      remember_false: "0"
